version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: workout-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: workout_tracker
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - workout-network

  backend:
    build: ./backend
    container_name: workout-backend
    restart: unless-stopped
    depends_on:
      - mysql
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=rootpassword
      - DB_NAME=workout_tracker
      - PORT=5000
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - workout-network
    command: npm run dev

  frontend:
    build: ./frontend
    container_name: workout-frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "3000:80"
    networks:
      - workout-network

volumes:
  mysql_data:

networks:
  workout-network:
    driver: bridge